name: build All

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v4
        with:
          repository: 'DaisukeDaisuke/dq9BattleEmulatorCollection.cpp'
          ref: 'erugiosu'
          path: 'dq9BattleEmulatorCollection'
      - uses: actions/checkout@v4
        with:
          path: 'dq9RTAVideoRecognitions'
      - name: Configure CMake
        working-directory: dq9BattleEmulatorCollection
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Cmake Build
        working-directory: dq9BattleEmulatorCollection
        run: cmake --build ./build --config ${{env.BUILD_TYPE}}
      - name: Move the executable file
        working-directory: dq9BattleEmulatorCollection
        run: |
          # Move the back-end program
          $source = "./build/${{env.BUILD_TYPE}}/newDirectory.exe"
          $destination = "../dq9RTAVideoRecognitions/erugiosu2/resource/cbe.exe"
          Rename-Item -Path $source -NewName $destination
      - name: Build C#
        working-directory: dq9RTAVideoRecognitions
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
      - name: Compress the publish directory
        working-directory: dq9RTAVideoRecognitions
        run: |
          $publishDir = "./erugiosu2/bin/Release/net6.0-windows/win-x64/publish"
          $outputZip = "./erugiosu2.zip"
          Compress-Archive -Path "$publishDir/*" -DestinationPath $outputZip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PublishedFiles
          path: "${{github.workspace}}/dq9RTAVideoRecognitions/erugiosu2.zip"
